#!/bin/bash
# find the directory where this script is located
script_dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
echo "copying config files"
cp -r $script_dir/home/{*,.*} "$HOME/"

echo "copying scripts into /usr/bin/"
sudo cp $script_dir/scripts/* "/usr/bin/"

echo "installing packages from package list files"
sudo pacman -Syu --noconfirm --needed - < $script_dir/arch-pkg-list
yay -S --noconfirm --needed - < $script_dir/aur-pkg-list
