#!/bin/bash
set -x
script_dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
# copy config files to user home
cp -r $script_dir/home/{*,.*} "$HOME/" 
# copy scripts into /usr/bin
sudo cp $script_dir/scripts/* "/usr/bin/"
# install pacages
sudo pacman -Syu --noconfirm --needed - < $script_dir/arch-pkg-list
yay -S --noconfirm --needed - < $script_dir/aur-pkg-list
